### ISSUE TITLE
CSS issue in home banner

### ISSUE THREAD

**Issue by Theepan97** [TriptaSingh/sabesian#8]
when you clearly watch the localhost home banner it has a border of a  light blue color. but on the original website it was filled by the banner image background. Here I attached the two images with a red mark of address bar Can we make our application the same as the original sabesansathananthan.github.io.  if you need any clarifications feel free to ask me.

![Screenshot (16)_LI](https://user-images.githubusercontent.com/63585695/80193131-ec0ec100-8635-11ea-906c-4ca7ab30536b.jpg)

![Screenshot (17)_LI](https://user-images.githubusercontent.com/63585695/80193153-f3ce6580-8635-11ea-9347-780ecdd07847.jpg)

**Comment by TriptaSingh** [comment]
Is it the background in banner. Or something is wrong wih URL

**Comment by Theepan97** [comment]
banner image as the whole background of home banner section
